### ISSUE TITLE
`GenerateAssembly` crash if the dynamic assembly references type of another assembly

### ISSUE THREAD

**Issue by Twinside** [Lokad/ILPack#9]
See the stack trace.

Exception: `The given key 'Envision.Back.Pages.IPage result' was not present in the dictionary.`

```
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Lokad.ILPack.IL.MethodBodyWriter.Write(BlobBuilder writer, IReadOnlyList`1 il, Func`2 getString, IReadOnlyDictionary`2 typeHandles, IReadOnlyDictionary`2 ctorRefHandles, IReadOnlyDictionary`2 fieldHandles, IReadOnlyDictionary`2 methodHandles) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\IL\MethodBodyWriter.cs:line 112
   at Lokad.ILPack.IL.MethodBodyStreamWriter.AddMethodBody(MethodBase methodBase) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\IL\MethodBodyStreamWriter.cs:line 56
   at Lokad.ILPack.AssemblyGenerator.GetOrCreateMethod(MethodInfo methodInfo) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.Methods.cs:line 59
   at Lokad.ILPack.AssemblyGenerator.CreatePropertiesForType(PropertyInfo[] properties) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.Properties.cs:line 64
   at Lokad.ILPack.AssemblyGenerator.GetOrCreateType(Type type) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.Types.cs:line 79
   at Lokad.ILPack.AssemblyGenerator.CreateTypes(Type[] types) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.Types.cs:line 13
   at Lokad.ILPack.AssemblyGenerator.CreateModules(Module[] moduleInfo) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.Modules.cs:line 21
   at Lokad.ILPack.AssemblyGenerator.GenerateAssemblyBytes() in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.cs:line 88
   at Lokad.ILPack.AssemblyGenerator.GenerateAssembly(String path) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.cs:line 115
   at ...
```

IPage is a type of our runtime system not created in the dynamic assembly.

**Comment by osman-turan** [comment]
I understand, you used `Envision.Back.Pages.IPage` interface in a method body without referencing it anywhere else (as type member, method parameter etc.), right?

**Comment by Twinside** [comment]
I can give you an example of assembly we're dumping (generated using net462), we've got the IPage directly referenced as class's private field.

[JotModule.zip](https://github.com/Lokad/ILPack/files/2941294/JotModule.zip)

**Comment by osman-turan** [comment]
@Twinside Thank you for the assembly!

One question, I thought ILPacker is .NET Core only, but you said you used in .NET Framework 4.6.2. If there is a plan to use in .NET Framework, I need to revise #13. Can you confirm it?

CC: @vermorel

**Comment by vermorel** [comment]
Ideally, ILPack would be .NET Standard, but if not possible or practical, then, we target .NET Core.

**Comment by Twinside** [comment]
We're cross compiling with `net462` just for the `AssemblyBuilder.Save()`, if it's .net core only, it's fine for us, we can still us conditional compilation if we want to support older framework (which is more than unlikely).

**Comment by osman-turan** [comment]
Thank you for the feedback! I'll focus on testing with .NET Framework 4.6.2 and .NET Core 2.1 after finishing this task (I plan to differentiate them at runtime - i.e. no `#if`). During my work, I noticed ILPack does not support generics type. As a first step of this bug, I need to fix #16.

**Comment by osman-turan** [comment]
It turns out your reported error is due to accessing a field from a method. Fields were serialized *after* methods. Commit #17 fixes it along initial generics support (requires for your case). Commit #18 adds a unit test about your case.

**Comment by osman-turan** [comment]
@Twinside Does it work with latest changes?

**Comment by Twinside** [comment]
Still not working for our use case, I get the following error:

```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: value
  Source=System.Reflection.Metadata
  StackTrace:
   at System.Reflection.Throw.ArgumentNull(String parameterName)
   at System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddString(String value)
   at Lokad.ILPack.AssemblyGenerator.ReserveTypeDefinition(Type type, TypeDefinitionMetadataOffset offset) in D:\buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.Types.cs:line 133
   at Lokad.ILPack.AssemblyGenerator.ReserveTypes(IEnumerable`1 types) in D:\buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.Types.cs:line 77
   at Lokad.ILPack.AssemblyGenerator.CreateTypes(IEnumerable`1 types) in D:\buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.Types.cs:line 50
   at Lokad.ILPack.AssemblyGenerator.CreateModules(IEnumerable`1 moduleInfo) in D:\buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.Modules.cs:line 22
   at Lokad.ILPack.AssemblyGenerator.GenerateAssemblyBytes(Assembly assembly) in D:\buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.cs:line 62
   at Lokad.ILPack.AssemblyGenerator.GenerateAssembly(Assembly assembly, String path) in D:\buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.cs:line 92
   at Envision.Back.Jot.Compilation.JotCompiler.DumpModule(String path) in C:\Users\VincentBerthoux\dev\main\Priceforge\src\Envision.Back\Jot\Compilation\JotCompiler.ModuleBuilder.cs:line 74
```

When in the debugguer, I can see that `type.Namespace` is null (AssemblyGenerator.Types.Cs:133)

```cs
            var typeHandle = _metadata.Builder.AddTypeDefinition(
                type.Attributes,
                _metadata.GetOrAddString(type.Namespace),
                _metadata.GetOrAddString(type.Name),
                baseTypeHandle,
                MetadataTokens.FieldDefinitionHandle(offset.FieldIndex + 1),
                MetadataTokens.MethodDefinitionHandle(offset.MethodIndex + 1));
```

**Comment by osman-turan** [comment]
@Twinside Thank you for good indicators. It should be fixed in #35.

**Comment by Twinside** [comment]
Sadly I've got another show-stopper:

```
   at Lokad.ILPack.AssemblyGenerator.VerifyEmittedHandle[TEntity,THandle](DefinitionMetadata`2 metadata, THandle handle) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.Helpers.cs:line 63
   at Lokad.ILPack.AssemblyGenerator.CreateConstructor(ConstructorInfo ctor) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.Constructors.cs:line 39
   at Lokad.ILPack.AssemblyGenerator.CreateConstructors(IEnumerable`1 constructors) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.Constructors.cs:line 44
   at Lokad.ILPack.AssemblyGenerator.CreateTypes(IEnumerable`1 types) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.Types.cs:line 61
   at Lokad.ILPack.AssemblyGenerator.CreateModules(IEnumerable`1 moduleInfo) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.Modules.cs:line 22
   at Lokad.ILPack.AssemblyGenerator.GenerateAssemblyBytes(Assembly assembly) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.cs:line 62
   at Lokad.ILPack.AssemblyGenerator.GenerateAssembly(Assembly assembly, String path) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.cs:line 92
   at Envision.Back.Jot.Compilation.JotCompiler.DumpModule(String path) in C:\Users\VincentBerthoux\dev\main\Priceforge\src\Envision.Back\Jot\Compilation\JotCompiler.ModuleBuilder.cs:line 74
```

The debugger is not cooperating this time I don't have much info beside the stack trace, don't hesitate to ask if you need more specific information

**Comment by osman-turan** [comment]
Thanks @Twinside ! It's most likely related to #39 (it's not merged into `master` yet) and it should be fixed now. Could you please retest and share your experience, please?

**Comment by Twinside** [comment]
Still crashing, new exception:
`Constructor cannot be found: Void .ctor(UInt32)`

```
   at Lokad.ILPack.Metadata.AssemblyMetadata.GetConstructorHandle(ConstructorInfo ctor) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\Metadata\AssemblyMetadata.Constructors.cs:line 27
   at Lokad.ILPack.IL.MethodBodyWriter.Write(IAssemblyMetadata metadata, IReadOnlyList`1 il) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\IL\MethodBodyWriter.cs:line 103
   at Lokad.ILPack.IL.MethodBodyStreamWriter.AddMethodBody(MethodBase methodBase) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\IL\MethodBodyStreamWriter.cs:line 39
   at Lokad.ILPack.AssemblyGenerator.CreateMethod(MethodInfo method) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.Methods.cs:line 31
   at Lokad.ILPack.AssemblyGenerator.CreateMethods(IEnumerable`1 methods) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.Methods.cs:line 70
   at Lokad.ILPack.AssemblyGenerator.CreateTypes(IEnumerable`1 types) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.Types.cs:line 63
   at Lokad.ILPack.AssemblyGenerator.CreateModules(IEnumerable`1 moduleInfo) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.Modules.cs:line 22
   at Lokad.ILPack.AssemblyGenerator.GenerateAssemblyBytes(Assembly assembly) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.cs:line 62
   at Lokad.ILPack.AssemblyGenerator.GenerateAssembly(Assembly assembly, String path) in D:\rainbow_buildAgent\work\8daee5e699edf9c0\src\AssemblyGenerator.cs:line 92
   at Envision.Back.Jot.Compilation.JotCompiler.DumpModule(String path) in ...
```

**Comment by osman-turan** [comment]
@Twinside Thank you for the feedback. Unfortunately, I'm almost clueless since I cannot access all referenced assemblies which makes it hard to replicate problem in my local environment. So, to increase my chance to narrow possibilities, I improved exception messages with more explicit reporting. Could you test with new changes and share exception message, please?

CC: @vermorel

**Comment by Twinside** [comment]
```
Constructor cannot be found: "Void .ctor(UInt32)" of "Envision.Back.Pages.Page`1[[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Envision.Back, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
Parameter name: ctor
```

the `Page<T>` type is written like that:

```cs
    /// <summary> A single array of a given value type. </summary>
    public sealed class Page<T> : IIndexablePage, IPageBuilder<T> where T : struct
    {
        public Page(T[] data) { Data = data; }

        public Page(uint size) : this(new T[size]) { }

        /// <summary> The array of data. </summary>
        public T[] Data { get; }

        /// <see cref="IPage.Count"/>
        /// <see cref="IPageBuilder.Count"/>
        public int Count => Data.Length;

        /* ... */
```

**Comment by Twinside** [comment]
Same errors at commit  c45367d

**Comment by Twinside** [comment]
I've fired up the gebugger, so we're trying to instantiate a `Page<bool>(uint32 size)` with the following information:

```
  | Name | Value | Type
-- | -- | -- | --
◢ | ctor | {Void .ctor(UInt32)} | System.Reflection.ConstructorInfo {System.Reflection.RuntimeConstructorInfo}
  | Attributes | Public \| HideBySig \| SpecialName \| RTSpecialName | System.Reflection.MethodAttributes
  | BindingFlags | Instance \| Public | System.Reflection.BindingFlags
  | CallingConvention | Standard \| HasThis | System.Reflection.CallingConventions
  | ContainsGenericParameters | false | bool
  | ▶ CustomAttributes | Count = 0 | System.Collections.Generic.IEnumerable<System.Reflection.CustomAttributeData> {System.Collections.ObjectModel.ReadOnlyCollection<System.Reflection.CustomAttributeData>}
  | ▶ DeclaringType | {Name = "Page`1" FullName = "Envision.Back.Pages.Page`1[[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"} | System.Type {System.RuntimeType}
  | FullName | "Envision.Back.Pages.Page`1[[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(UInt32)" | string
  | InvocationFlags | INVOCATION_FLAGS_INITIALIZED \| INVOCATION_FLAGS_IS_CTOR | System.Reflection.INVOCATION_FLAGS
  | IsAbstract | false | bool
  | IsAssembly | false | bool
  | IsConstructedGenericMethod | false | bool
  | IsConstructor | true | bool
  | IsFamily | false | bool
  | IsFamilyAndAssembly | false | bool
  | IsFamilyOrAssembly | false | bool
  | IsFinal | false | bool
  | IsGenericMethod | false | bool
  | IsGenericMethodDefinition | false | bool
  | IsHideBySig | true | bool
  | IsPrivate | false | bool
  | IsPublic | true | bool
  | IsSecurityCritical | true | bool
  | IsSecuritySafeCritical | false | bool
  | IsSecurityTransparent | false | bool
  | IsSpecialName | true | bool
  | IsStatic | false | bool
  | IsVirtual | false | bool
  | MemberType | Constructor | System.Reflection.MemberTypes
  | MetadataToken | 100664536 | int
  | ▶ MethodHandle | {System.RuntimeMethodHandle} | System.RuntimeMethodHandle
  | MethodImplementationFlags | IL | System.Reflection.MethodImplAttributes
  | ▶ Module | {Envision.Back.dll} | System.Reflection.Module {System.Reflection.RuntimeModule}
  | Name | ".ctor" | string
  | ▶ ReflectedType | {Name = "Page`1" FullName = "Envision.Back.Pages.Page`1[[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"} | System.Type {System.RuntimeType}
  | ▶ ReflectedTypeInternal | {Name = "Page`1" FullName = "Envision.Back.Pages.Page`1[[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"} | System.RuntimeType
  | ▶ Signature | {System.Signature} | System.Signature
  | ▶ System.IRuntimeMethodInfo.Value | {System.RuntimeMethodHandleInternal} | System.RuntimeMethodHandleInternal
  | _empty1 | null | object
  | _empty2 | null | object
  | _empty3 | null | object
  | m_bindingFlags | Instance \| Public | System.Reflection.BindingFlags
  | ▶ m_declaringType | {Name = "Page`1" FullName = "Envision.Back.Pages.Page`1[[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"} | System.RuntimeType
  | ▶ m_handle | 0x00007ffc85a4cf70 | System.IntPtr
  | m_invocationFlags | INVOCATION_FLAGS_INITIALIZED \| INVOCATION_FLAGS_IS_CTOR | System.Reflection.INVOCATION_FLAGS
  | m_methodAttributes | Public \| HideBySig \| SpecialName \| RTSpecialName | System.Reflection.MethodAttributes
  | ▶ m_parameters | {System.Reflection.ParameterInfo[1]} | System.Reflection.ParameterInfo[]
  | ▶ m_reflectedTypeCache | {System.RuntimeType.RuntimeTypeCache} | System.RuntimeType.RuntimeTypeCache
  | ▶ m_signature | {System.Signature} | System.Signature
  | m_toString | "Void .ctor(UInt32)" | string
```

While the only matching constructor in `AssemblyMetadata._ctorRefHandles` is the following one:

```

  | Name | Value | Type
-- | -- | -- | --
◢ | [14] | {[Void .ctor(UInt32), System.Reflection.Metadata.MemberReferenceHandle]} | System.Collections.Generic.KeyValuePair<System.Reflection.ConstructorInfo, System.Reflection.Metadata.MemberReferenceHandle>
  | ◢ Key | {Void .ctor(UInt32)} | System.Reflection.ConstructorInfo {System.Reflection.RuntimeConstructorInfo}
  | Attributes | Public \| HideBySig \| SpecialName \| RTSpecialName | System.Reflection.MethodAttributes
  | BindingFlags | Instance \| Public | System.Reflection.BindingFlags
  | CallingConvention | Standard \| HasThis | System.Reflection.CallingConventions
  | ContainsGenericParameters | true | bool
  | ▶ CustomAttributes | Count = 0 | System.Collections.Generic.IEnumerable<System.Reflection.CustomAttributeData> {System.Collections.ObjectModel.ReadOnlyCollection<System.Reflection.CustomAttributeData>}
  | ▶ DeclaringType | {Name = "Page`1" FullName = "Envision.Back.Pages.Page`1"} | System.Type {System.RuntimeType}
  | FullName | "Envision.Back.Pages.Page`1..ctor(UInt32)" | string
  | InvocationFlags | INVOCATION_FLAGS_INITIALIZED \| INVOCATION_FLAGS_NO_INVOKE \| INVOCATION_FLAGS_IS_CTOR | System.Reflection.INVOCATION_FLAGS
  | IsAbstract | false | bool
  | IsAssembly | false | bool
  | IsConstructedGenericMethod | false | bool
  | IsConstructor | true | bool
  | IsFamily | false | bool
  | IsFamilyAndAssembly | false | bool
  | IsFamilyOrAssembly | false | bool
  | IsFinal | false | bool
  | IsGenericMethod | false | bool
  | IsGenericMethodDefinition | false | bool
  | IsHideBySig | true | bool
  | IsPrivate | false | bool
  | IsPublic | true | bool
  | IsSecurityCritical | true | bool
  | IsSecuritySafeCritical | false | bool
  | IsSecurityTransparent | false | bool
  | IsSpecialName | true | bool
  | IsStatic | false | bool
  | IsVirtual | false | bool
  | MemberType | Constructor | System.Reflection.MemberTypes
  | MetadataToken | 100664536 | int
  | ▶ MethodHandle | {System.RuntimeMethodHandle} | System.RuntimeMethodHandle
  | MethodImplementationFlags | IL | System.Reflection.MethodImplAttributes
  | ▶ Module | {Envision.Back.dll} | System.Reflection.Module {System.Reflection.RuntimeModule}
  | Name | ".ctor" | string
  | ▶ ReflectedType | {Name = "Page`1" FullName = "Envision.Back.Pages.Page`1"} | System.Type {System.RuntimeType}
  | ▶ ReflectedTypeInternal | {Name = "Page`1" FullName = "Envision.Back.Pages.Page`1"} | System.RuntimeType
  | ▶ Signature | {System.Signature} | System.Signature
  | ▶ System.IRuntimeMethodInfo.Value | {System.RuntimeMethodHandleInternal} | System.RuntimeMethodHandleInternal
  | _empty1 | null | object
  | _empty2 | null | object
  | _empty3 | null | object
  | m_bindingFlags | Instance \| Public | System.Reflection.BindingFlags
  | ▶ m_declaringType | {Name = "Page`1" FullName = "Envision.Back.Pages.Page`1"} | System.RuntimeType
  | ▶ m_handle | 0x00007ffc85a4b860 | System.IntPtr
  | m_invocationFlags | INVOCATION_FLAGS_INITIALIZED \| INVOCATION_FLAGS_NO_INVOKE \| INVOCATION_FLAGS_IS_CTOR | System.Reflection.INVOCATION_FLAGS
  | m_methodAttributes | Public \| HideBySig \| SpecialName \| RTSpecialName | System.Reflection.MethodAttributes
  | ▶ m_parameters | {System.Reflection.ParameterInfo[1]} | System.Reflection.ParameterInfo[]
  | ▶ m_reflectedTypeCache | {System.RuntimeType.RuntimeTypeCache} | System.RuntimeType.RuntimeTypeCache
  | ▶ m_signature | {System.Signature} | System.Signature
  | m_toString | "Void .ctor(UInt32)" | string
  | ▶ Static members |   |  
  | ◢ Value | {System.Reflection.Metadata.MemberReferenceHandle} | System.Reflection.Metadata.MemberReferenceHandle
  | IsNil | false | bool
  | RowId | 15 | int
  | _rowId | 15 | int
```

We can see that we store the type generic version only in `_ctorRefHandles`
By hacking around in `AssemblyMetadata.Constructor.cs`, I can manage to generate the final assembly:

```cs
        public EntityHandle GetConstructorHandle(ConstructorInfo ctor)
        {
            if (TryGetConstructorDefinition(ctor, out var metadata))
            {
                return metadata.Handle;
            }

            if (IsReferencedType(ctor.DeclaringType))
            {
                // Make sure type reference and all public constructors are resolved
                ResolveTypeReference(ctor.DeclaringType);

                // This is where we cheat
                if (ctor.DeclaringType.IsGenericType)
                {
                    // we try to find the same constructor attached to the generic type
                    ctor = ctor
                        .DeclaringType
                        .GetGenericTypeDefinition()
                        .GetConstructor(ctor.GetParameters().Select(e => e.ParameterType).ToArray());
                }
                

                if (_ctorRefHandles.TryGetValue(ctor, out var handle))
                {
                    return handle;
                }
            }

            throw new ArgumentException($"Constructor cannot be found: {MetadataHelper.GetFriendlyName(ctor)}",
                nameof(ctor));
        }
```

While some assembly is generated, PEVerify is not happy with it:

```
Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The located assembly's manifest definition does not match the assembly reference.
The located assembly's manifest definition does not match the assembly reference.
2 Error(s) Verifying JotModule.dll
```

And the assembly opened in dotpeek has some weird construct to say the list

```cs
      // ...
      page = (Page<bool>) new Page<>((uint) _param4);
      // ...
```

so my hack is clearly not a viable solution

**Comment by osman-turan** [comment]
@Twinside Thanks for detailed information. I've just tested similar idea (instantiation of a referenced generic type with value type generic parameter: `List<int>`) with #82. dotPeek has successfully decompiled the generated assembly.

```cs
private List<int> _genericField;

public void CreateGenericField()
{
    this._genericField = new List<int>();
}
```

**Comment by Twinside** [comment]
Last commits generate an assembly, closing
